remote_theme: "owasp/www--site-theme"

#override default star and watch buttons
code_user: maryam
code_repo: maryam

# core files/folders to exclude
exclude:
 - README.md

plugins:
 - jekyll-include-cache-0.2.0
